const modal=document.getElementById('modal'), content=document.getElementById('modal-content');
const demo={used:Number(localStorage.getItem('uncover_used')||0),liked:false,approved:false};
function show(type){modal.classList.add('open'); if(type==='signup') content.innerHTML=`<h2>Join Uncover</h2><p>Start with three private conversations, free.</p><div class="notice">18+ community • Your full profile stays hidden until mutual approval.</div><form class="form" id="signupForm"><input type="text" placeholder="Display name" required><input type="email" placeholder="Email" required><input type="password" placeholder="Password" required><button class="btn dark" type="submit">Create free account</button></form>`; else if(type==='login') content.innerHTML=`<h2>Welcome back</h2><p>Continue your private connections.</p><form class="form" id="loginForm"><input type="email" placeholder="Email" required><input type="password" placeholder="Password" required><button class="btn dark">Log in</button></form>`; else content.innerHTML=`<h2>Uncover Plus</h2><p>Unlimited private conversations and advanced discovery for <b>₹299/month</b>.</p><div class="notice">This prototype is ready for Stripe integration. No payment is collected in this demo.</div><button class="btn pink full" id="demoPay">Continue to secure checkout</button>`; document.getElementById('signupForm')?.addEventListener('submit',e=>{e.preventDefault();startDemo()}); document.getElementById('loginForm')?.addEventListener('submit',e=>{e.preventDefault();startDemo()}); document.getElementById('demoPay')?.addEventListener('click',()=>{content.innerHTML='<h2>Premium ready</h2><p>In production, this button will open Stripe Checkout and activate your subscription after a verified webhook.</p><div class="reveal">✓ Payment flow placeholder configured</div>'})}
function startDemo(){content.innerHTML=`<h2>Your first conversation</h2><p>You are browsing anonymously. No full profile is visible yet.</p><div class="demo-card"><strong>Someone · 26</strong><span>Interests: travel · books · music</span></div><div class="demo"><button class="btn dark" id="chatBtn">Start private chat</button><span class="counter">${Math.max(0,3-demo.used)} free conversations remaining</span></div>`;document.getElementById('chatBtn').onclick=chat}
function chat(){if(demo.used>=3){show('premium');return} demo.used++;localStorage.setItem('uncover_used',demo.used);content.innerHTML=`<h2>Private chat</h2><p>You don't see each other's profiles yet.</p><div class="demo-card"><strong>Someone</strong><p>“Hey! What is something you could talk about for hours?”</p><p style="text-align:right">“Probably travel and finding hidden places.”</p><p>“Nice. I love that too. What's your ideal weekend?”</p></div><button class="btn pink full" id="likeBtn">♡ I like this connection</button><p class="counter">${Math.max(0,3-demo.used)} free conversations remaining</p>`;document.getElementById('likeBtn').onclick=like}
function like(){demo.liked=true;content.innerHTML=`<h2>Connection request sent</h2><p>You liked the conversation. Their profile will stay hidden unless they like you back.</p><div class="notice">Waiting for mutual approval…</div><button class="btn dark full" id="approveDemo">Simulate their approval</button>`;document.getElementById('approveDemo').onclick=reveal}
function reveal(){demo.approved=true;content.innerHTML=`<h2>It's mutual. ✨</h2><p>You both approved the connection, so your profiles can now be revealed.</p><div class="reveal"><b>Profile revealed</b><br>Alex, 26 · Designer<br>Travel · Books · Music<br>8 km away</div><button class="btn dark full" onclick="closeModal()">Continue chatting</button>`}
function closeModal(){modal.classList.remove('open')}
document.querySelectorAll('[data-open]').forEach(b=>b.addEventListener('click',()=>show(b.dataset.open)));document.getElementById('close').onclick=closeModal;modal.addEventListener('click',e=>{if(e.target===modal)closeModal()});
